### ISSUE TITLE
I cannot get the same performance in hermes paper

### ISSUE THREAD

**Issue by qingyuShi475** [snowzjx/ns3-load-balance#1]
Would you mind giving a best parameter settings for hermes in file "conga-simulation-large.cc" and a well-matched python script for a 8x8 spine-leaf topology?
I have run many times using the recommended setting for hermes, I think the default parameter settings you list in this repository is misleading. Or would you mind giving a explanation for this?
Thanks.

**Comment by snowzjx** [comment]
Could you help to check this ? @hongzhangblaze

**Comment by hongzhangblaze** [comment]
I just check the recommended settings documentation. One mistake was found that the recommended value for TLBHighRTT and TLBBetterPathRTT should be switched with each other (i.e., 180 for HighRTT and 100 for BetterRTT). Sorry for this mistake in documentation and you may try if it solves the problem.

**Comment by qingyuShi475** [comment]
OK, I will check this. Thank u very much!  And I wanna know if I do the Evaluation in a 4x4 spine-leaf, do I need to change the parameter settings? Thanks.

**Comment by hongzhangblaze** [comment]
The parameter settings remain the same for 4x4. One has to change parameters (as suggested in the readme file) for the failure cases though.

**Comment by qingyuShi475** [comment]
Thank you very much for your help.
