### ISSUE TITLE
请问，得出论文结果的仿真时长也是0-0.1-0.25吗

### ISSUE THREAD

**Issue by zjs19960124** [snowzjx/ns3-load-balance#2]
START_TIME 0
FLOW_LAUNCH_TIME 0.1
END_TIME 0.25
这些需要改吗？

**Comment by hongzhangblaze** [comment]
大多数实验的setting是 
StartTime: 0
EndTime: 7 
FlowLaunchEndTime: 2

**Comment by zjs19960124** [comment]
谢谢！
