### ISSUE TITLE
求助，无法得出Hermes论文中的结果

### ISSUE THREAD

**Issue by zjs19960124** [snowzjx/ns3-load-balance#3]
使用DCTCP，TLB参数设置是
uint32_t TLBMinRTT = 60;
uint32_t TLBHighRTT = 180;
uint32_t TLBPoss = 50;
uint32_t TLBBetterPathRTT = 100;
uint32_t TLBT1 = 60;
double TLBECNPortionLow = 0.1;
uint32_t TLBRunMode = 12;
bool TLBProbingEnable = true;
uint32_t TLBProbingInterval = 100;
bool TLBSmooth = true;
bool TLBRerouting = true;
uint32_t TLBDREMultiply = 5;
uint32_t TLBS = 600000;
bool TLBReverseACK = false;
uint32_t TLBFlowletTimeout = 150;
uint32_t quantifyRTTBase = 10;
其他参数设置：
double START_TIME = 0.0;
double END_TIME = 7;
double FLOW_LAUNCH_END_TIME = 2
int SERVER_COUNT = 16;
int SPINE_COUNT = 8;
int LEAF_COUNT = 8;
int LINK_COUNT = 1;
其余参数保持默认值，Web-Search(DCTCP_CDF.txt)与Data-Mining(VL2_DCF.txt)下测试TLB结果都得不到Hermes论文中的结果

另外，请检查src/tlb/model/ipv4-tlb.cc文件的第1050、1062、1171、1183行，if条件里的runmode均为RTT_DRE（此条更正后也未能得出Hermes论文的结果）
其余方案（除DRILL外）结果均正常

希望能给予帮助，谢谢！

**Comment by hongzhangblaze** [comment]
代码在做完实验后又做了一些改动且没进行测试 所以可能引入了一些问题。我想问下目前你run的是哪个实验，然后差距是多少呢？另外你微信多少，我想可以拉个讨论组讨论方便点。

**Comment by zjs19960124** [comment]
您好！
我的微信号是zjs19960124，因为现在正在准备投稿INFOCOM2019，计划将Hermes作为对比方案之一，所以也希望您告知得出Hermes论文的代码是哪个版本，这样我能快速地得出仿真结果，谢谢！

**Comment by qingyuShi475** [comment]
我想是ipv4-tlb.cc的1339行if语句判断有问题，和原论文对比可以看出来，sorry现在才看到问题，我是修改了这个地方后重新测试，获得了和Hermes类似的性能结果。

**Comment by hongzhangblaze** [comment]
多谢多谢！我刚看了一下，是大小于号写反了是么？ 这个是最近一次更新的时候引入的错误，囧。

**Comment by qingyuShi475** [comment]
不客气哈哈确实是这样
